---
title: "SCE1 gbkmr noselection summarization"
author: "Zilan Chai"
date: '2022-10-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(dplyr)
library(data.table)
library(ggplot2) 
library(haven)
library(dplyr)
library(readstata13) 
library(corrplot)
library(mice)
library(pastecs)
#library(bkmr) 
library(knitr)
```

```{r}
setwd("/Users/zilanchai/Docs/FinalSimSettings/SCE1_hiesel")
sim_popn <- readRDS("popn_highcor_nonlinearLY_3.rds")  
```

This script summarizes the Estimate, Bias, Relative Bias,  MSE, Coverage, of `bkmr with grouped hierarchical variable selection` for Scenario 1.  

```{r}

Ya = c()
Yastar = c()

for (i in 1:500) {
  file = paste0("Ya_", i,".rds")
  path = file.path(file)
  if(file.exists(path)==FALSE)   {
    next
  }
  temp = readRDS(paste0("Ya_", i, ".rds"))
  Ya[i] = mean(temp)
}

for (i in 1:500) {
  file = paste0("Yastar_", i,".rds")
  path = file.path(file)
  if(file.exists(path)==FALSE)   {
    next
  }
  temp = readRDS(paste0("Yastar_", i, ".rds"))
  Yastar[i] = mean(temp)
}

```


```{r}
diff_True = -0.7207878

diff_gbkmr = Yastar - Ya

est = mean(diff_gbkmr)

bias = est - diff_True
var = var(diff_gbkmr)
RelativeBias = bias/diff_True

MSE = bias^2 + var

inInterval = c()

 fun <- function(diff_True){
  for (i in 1:500) {
    file_a = paste0("Ya_", i,".rds")
    path_a = file.path(file_a)
  
  file_astar = paste0("Yastar_", i,".rds")
  path_astar = file.path(file_astar)
  
  
  if(file.exists(path_a)==FALSE || file.exists(path_astar)==FALSE ) { 
    next  
  }
  
  Ya_temp = readRDS(file_a)
  Yastar_temp = readRDS(file_astar)
  diff_tmp = Yastar_temp - Ya_temp 
   
  upper = quantile(diff_tmp, .975) 
  lower = quantile(diff_tmp, .025) 
  t=sum(upper >= diff_True & lower <= diff_True)
  inInterval = c(inInterval, t) 
  } 
   
   
coverage = mean(inInterval)
return(coverage)
}

coverage_gBKMRnosel = fun(diff_True)


cbind(est, bias, RelativeBias, var, MSE, coverage_gBKMRnosel)
``` 
